import styles from "../styles/Layout.module.css";
import type { ReactNode } from "react";
import NavBar from "./NavBar";
import Footer from "./Footer";
import Head from "next/head";
import { useRouter } from "next/router";
import { navBarSetting } from "../NavBarSetting";
import { Text } from "@nextui-org/react";
import ScrollToTop from "./ScrollToTop"

type rp2hn = {
  [key: string]: string;
};
const routerPath2HeadName: rp2hn = {};
navBarSetting.map((navItemProps) => {
  if (navItemProps.to) {
    // @ts-ignore
    routerPath2HeadName[navItemProps.to] = navItemProps.description;
    routerPath2HeadName['/#'] = "Home"
  }
});

type LayoutProps = {
  children: ReactNode;
};

export default function Layout({ children }: LayoutProps) {
  const router = useRouter();
  
  const routerPath = router.asPath
  const rootPath = `/${routerPath.split('/')[1]}`
  let titleName = routerPath2HeadName[rootPath]
  if (!titleName) {titleName = "404"}

  return (
    <>
      <Head>
        <title>Tianyu | {titleName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <NavBar />
        <div className={styles.content}>
          <ScrollToTop />
          <div style={{ display: "flex" }}>
            <Text h1> {titleName}</Text>
            <Text
              h1
              css={{ textGradient: "45deg, $pink400 0%, $blue600 100%" }}
            >
              _
            </Text>
          </div>
          {children}
        </div>
        <Footer />
      </div>
    </>
  );
}
